server:
  port:
    8089

spring:
  security:
    user:
      name:
        user
      password:
        pwd

  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration